// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABJbQ6BTM8wjzitXH0KpYbR7ePd8S3LtQ',
    appId: '1:1053215052368:web:10ee5c09aa1e6854543755',
    messagingSenderId: '1053215052368',
    projectId: 'delta-kim',
    authDomain: 'delta-kim.firebaseapp.com',
    storageBucket: 'delta-kim.firebasestorage.app',
    measurementId: 'G-EXQ97J68FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnGoDF8pL4QT7YLiT3WSwkFy1l4bdbQUc',
    appId: '1:1053215052368:android:8e36e32155a5982a543755',
    messagingSenderId: '1053215052368',
    projectId: 'delta-kim',
    storageBucket: 'delta-kim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdXTrhY3EdFbyUPcF5SXvtmKInUfWv_1k',
    appId: '1:1053215052368:ios:462f7098f9c52798543755',
    messagingSenderId: '1053215052368',
    projectId: 'delta-kim',
    storageBucket: 'delta-kim.firebasestorage.app',
    iosBundleId: 'com.example.deltaMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdXTrhY3EdFbyUPcF5SXvtmKInUfWv_1k',
    appId: '1:1053215052368:ios:462f7098f9c52798543755',
    messagingSenderId: '1053215052368',
    projectId: 'delta-kim',
    storageBucket: 'delta-kim.firebasestorage.app',
    iosBundleId: 'com.example.deltaMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABJbQ6BTM8wjzitXH0KpYbR7ePd8S3LtQ',
    appId: '1:1053215052368:web:eec459e1c6a6a204543755',
    messagingSenderId: '1053215052368',
    projectId: 'delta-kim',
    authDomain: 'delta-kim.firebaseapp.com',
    storageBucket: 'delta-kim.firebasestorage.app',
    measurementId: 'G-Z8VG5FH2L6',
  );
}
